### PR TITLE
 Change 'var' into const or let. Update npm packages. Eslint fixes

### PR DESCRIPTION
**Pull request by s0j0hn**

### CODE REVIEW

**Comment by s0j0hn** [comment]
WIP

**Comment by s0j0hn** [comment]
Default eslint configuration https://eslint.org/docs/user-guide/getting-started.

If there is some special one for this repo need or recommaded is good ?

**Comment by PierreBrisorgueil** [comment]
@s0j0hn thx :) ! I suggest to use airbnb config like meanJs https://github.com/meanjs/mean/blob/master/package.json

@techla ?

**Comment by techla** [comment]
According to https://medium.com/@uistephen/style-guides-for-linting-ecmascript-2015-eslint-common-google-airbnb-6c25fd3dff0, the eslint recommended set "is not a very strongly opinionated style set". Rbnb on the other hand imposes stronger conditions and by the way stress the normalization of the coding style.

**Comment by PierreBrisorgueil** [comment]
:+1: we will end the v1 soon, do you think we will be able to merge quickly ?

**Comment by s0j0hn** [comment]
travis has trouble with yarn

**Comment by PierreBrisorgueil** [comment]
ok, consider it ok, i merge in dev in order to continue the work and finish the v1 :) 
I would have a look on test and travis

**Pull request merged**
